# Allocator Agent Configuration
# Interface configuration for console, HTTP (REST/MCP), and MCP stdio

interfaces:
  session_ttl: 3600  # Session timeout in seconds

  console:
    enabled: true  # Interactive console (default)

  http:
    enabled: false  # HTTP server (REST API + MCP over HTTP)
    host: "0.0.0.0"
    port: 8000
    rest_api: true
    mcp_http: true
    mcp_mount_path: "/mcp"

  mcp_stdio:
    enabled: false  # MCP stdio mode for Claude Desktop integration
