# Allocator Agent Configuration
# Override global agent-kit settings for capital allocation analysis

# Max iterations for complex multi-step analysis
max_iterations: 25

# Additional agent-specific settings can be added here
